name: svg-rasterizer
services:
  - name: web
    git:
      branch: main
      repo_clone_url: https://github.com/WietseWind/svg-rasterizer.git
    dockerfile_path: Dockerfile
    instance_count: 1
    instance_size_slug: basic-xs
    http_port: 8080
    envs:
      - key: REDIS_URL
        type: SECRET # This will be set in DigitalOcean dashboard
      - key: RUST_LOG
        value: "info"
    health_check:
      http_path: /health
      port: 8080
      period_seconds: 10
      timeout_seconds: 5
      failure_threshold: 3
      success_threshold: 1